/*
PostBoost API

Testing WorkspacesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package postboost

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_postboost_WorkspacesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WorkspacesAPIService AddUserToWorkspace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var workspaceUuid string

		resp, httpRes, err := apiClient.WorkspacesAPI.AddUserToWorkspace(context.Background(), workspaceUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspacesAPIService CreateWorkspace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WorkspacesAPI.CreateWorkspace(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspacesAPIService DeleteWorkspace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var workspaceUuid string

		resp, httpRes, err := apiClient.WorkspacesAPI.DeleteWorkspace(context.Background(), workspaceUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspacesAPIService DeleteWorkspacesBulk", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WorkspacesAPI.DeleteWorkspacesBulk(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspacesAPIService GetWorkspace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var workspaceUuid string

		resp, httpRes, err := apiClient.WorkspacesAPI.GetWorkspace(context.Background(), workspaceUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspacesAPIService ListWorkspaces", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WorkspacesAPI.ListWorkspaces(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspacesAPIService RemoveUserFromWorkspace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var workspaceUuid string

		resp, httpRes, err := apiClient.WorkspacesAPI.RemoveUserFromWorkspace(context.Background(), workspaceUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspacesAPIService UpdateWorkspace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var workspaceUuid string

		resp, httpRes, err := apiClient.WorkspacesAPI.UpdateWorkspace(context.Background(), workspaceUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspacesAPIService UpdateWorkspaceUser", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var workspaceUuid string

		resp, httpRes, err := apiClient.WorkspacesAPI.UpdateWorkspaceUser(context.Background(), workspaceUuid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
