/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChangeSubscriptionPlanRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChangeSubscriptionPlanRequest{}

// ChangeSubscriptionPlanRequest struct for ChangeSubscriptionPlanRequest
type ChangeSubscriptionPlanRequest struct {
	PlanId int32 `json:"plan_id"`
	Cycle string `json:"cycle"`
	Prorate bool `json:"prorate"`
	BillingImmediately bool `json:"billing_immediately"`
}

type _ChangeSubscriptionPlanRequest ChangeSubscriptionPlanRequest

// NewChangeSubscriptionPlanRequest instantiates a new ChangeSubscriptionPlanRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChangeSubscriptionPlanRequest(planId int32, cycle string, prorate bool, billingImmediately bool) *ChangeSubscriptionPlanRequest {
	this := ChangeSubscriptionPlanRequest{}
	this.PlanId = planId
	this.Cycle = cycle
	this.Prorate = prorate
	this.BillingImmediately = billingImmediately
	return &this
}

// NewChangeSubscriptionPlanRequestWithDefaults instantiates a new ChangeSubscriptionPlanRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChangeSubscriptionPlanRequestWithDefaults() *ChangeSubscriptionPlanRequest {
	this := ChangeSubscriptionPlanRequest{}
	return &this
}

// GetPlanId returns the PlanId field value
func (o *ChangeSubscriptionPlanRequest) GetPlanId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value
// and a boolean to check if the value has been set.
func (o *ChangeSubscriptionPlanRequest) GetPlanIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanId, true
}

// SetPlanId sets field value
func (o *ChangeSubscriptionPlanRequest) SetPlanId(v int32) {
	o.PlanId = v
}

// GetCycle returns the Cycle field value
func (o *ChangeSubscriptionPlanRequest) GetCycle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cycle
}

// GetCycleOk returns a tuple with the Cycle field value
// and a boolean to check if the value has been set.
func (o *ChangeSubscriptionPlanRequest) GetCycleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cycle, true
}

// SetCycle sets field value
func (o *ChangeSubscriptionPlanRequest) SetCycle(v string) {
	o.Cycle = v
}

// GetProrate returns the Prorate field value
func (o *ChangeSubscriptionPlanRequest) GetProrate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Prorate
}

// GetProrateOk returns a tuple with the Prorate field value
// and a boolean to check if the value has been set.
func (o *ChangeSubscriptionPlanRequest) GetProrateOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prorate, true
}

// SetProrate sets field value
func (o *ChangeSubscriptionPlanRequest) SetProrate(v bool) {
	o.Prorate = v
}

// GetBillingImmediately returns the BillingImmediately field value
func (o *ChangeSubscriptionPlanRequest) GetBillingImmediately() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.BillingImmediately
}

// GetBillingImmediatelyOk returns a tuple with the BillingImmediately field value
// and a boolean to check if the value has been set.
func (o *ChangeSubscriptionPlanRequest) GetBillingImmediatelyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingImmediately, true
}

// SetBillingImmediately sets field value
func (o *ChangeSubscriptionPlanRequest) SetBillingImmediately(v bool) {
	o.BillingImmediately = v
}

func (o ChangeSubscriptionPlanRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChangeSubscriptionPlanRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plan_id"] = o.PlanId
	toSerialize["cycle"] = o.Cycle
	toSerialize["prorate"] = o.Prorate
	toSerialize["billing_immediately"] = o.BillingImmediately
	return toSerialize, nil
}

func (o *ChangeSubscriptionPlanRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plan_id",
		"cycle",
		"prorate",
		"billing_immediately",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChangeSubscriptionPlanRequest := _ChangeSubscriptionPlanRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChangeSubscriptionPlanRequest)

	if err != nil {
		return err
	}

	*o = ChangeSubscriptionPlanRequest(varChangeSubscriptionPlanRequest)

	return err
}

type NullableChangeSubscriptionPlanRequest struct {
	value *ChangeSubscriptionPlanRequest
	isSet bool
}

func (v NullableChangeSubscriptionPlanRequest) Get() *ChangeSubscriptionPlanRequest {
	return v.value
}

func (v *NullableChangeSubscriptionPlanRequest) Set(val *ChangeSubscriptionPlanRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChangeSubscriptionPlanRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChangeSubscriptionPlanRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChangeSubscriptionPlanRequest(val *ChangeSubscriptionPlanRequest) *NullableChangeSubscriptionPlanRequest {
	return &NullableChangeSubscriptionPlanRequest{value: val, isSet: true}
}

func (v NullableChangeSubscriptionPlanRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChangeSubscriptionPlanRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


