/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"fmt"
)

// DeleteMode - `app_only` — delete from PostBoost only - `app_and_social` — delete from PostBoost and the social platform - `social_only` — delete from the social platform only 
type DeleteMode string

// List of DeleteMode
const (
	APP_ONLY DeleteMode = "app_only"
	APP_AND_SOCIAL DeleteMode = "app_and_social"
	SOCIAL_ONLY DeleteMode = "social_only"
)

// All allowed values of DeleteMode enum
var AllowedDeleteModeEnumValues = []DeleteMode{
	"app_only",
	"app_and_social",
	"social_only",
}

func (v *DeleteMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DeleteMode(value)
	for _, existing := range AllowedDeleteModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DeleteMode", value)
}

// NewDeleteModeFromValue returns a pointer to a valid DeleteMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDeleteModeFromValue(v string) (*DeleteMode, error) {
	ev := DeleteMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DeleteMode: valid values are %v", v, AllowedDeleteModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DeleteMode) IsValid() bool {
	for _, existing := range AllowedDeleteModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to DeleteMode value
func (v DeleteMode) Ptr() *DeleteMode {
	return &v
}

type NullableDeleteMode struct {
	value *DeleteMode
	isSet bool
}

func (v NullableDeleteMode) Get() *DeleteMode {
	return v.value
}

func (v *NullableDeleteMode) Set(val *DeleteMode) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteMode) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteMode(val *DeleteMode) *NullableDeleteMode {
	return &NullableDeleteMode{value: val, isSet: true}
}

func (v NullableDeleteMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

