/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// InitiateRemoteUpload201Response - struct for InitiateRemoteUpload201Response
type InitiateRemoteUpload201Response struct {
	InitiateRemoteUpload201ResponseOneOf *InitiateRemoteUpload201ResponseOneOf
	Media *Media
}

// InitiateRemoteUpload201ResponseOneOfAsInitiateRemoteUpload201Response is a convenience function that returns InitiateRemoteUpload201ResponseOneOf wrapped in InitiateRemoteUpload201Response
func InitiateRemoteUpload201ResponseOneOfAsInitiateRemoteUpload201Response(v *InitiateRemoteUpload201ResponseOneOf) InitiateRemoteUpload201Response {
	return InitiateRemoteUpload201Response{
		InitiateRemoteUpload201ResponseOneOf: v,
	}
}

// MediaAsInitiateRemoteUpload201Response is a convenience function that returns Media wrapped in InitiateRemoteUpload201Response
func MediaAsInitiateRemoteUpload201Response(v *Media) InitiateRemoteUpload201Response {
	return InitiateRemoteUpload201Response{
		Media: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *InitiateRemoteUpload201Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into InitiateRemoteUpload201ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.InitiateRemoteUpload201ResponseOneOf)
	if err == nil {
		jsonInitiateRemoteUpload201ResponseOneOf, _ := json.Marshal(dst.InitiateRemoteUpload201ResponseOneOf)
		if string(jsonInitiateRemoteUpload201ResponseOneOf) == "{}" { // empty struct
			dst.InitiateRemoteUpload201ResponseOneOf = nil
		} else {
			if err = validator.Validate(dst.InitiateRemoteUpload201ResponseOneOf); err != nil {
				dst.InitiateRemoteUpload201ResponseOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.InitiateRemoteUpload201ResponseOneOf = nil
	}

	// try to unmarshal data into Media
	err = newStrictDecoder(data).Decode(&dst.Media)
	if err == nil {
		jsonMedia, _ := json.Marshal(dst.Media)
		if string(jsonMedia) == "{}" { // empty struct
			dst.Media = nil
		} else {
			if err = validator.Validate(dst.Media); err != nil {
				dst.Media = nil
			} else {
				match++
			}
		}
	} else {
		dst.Media = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.InitiateRemoteUpload201ResponseOneOf = nil
		dst.Media = nil

		return fmt.Errorf("data matches more than one schema in oneOf(InitiateRemoteUpload201Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(InitiateRemoteUpload201Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src InitiateRemoteUpload201Response) MarshalJSON() ([]byte, error) {
	if src.InitiateRemoteUpload201ResponseOneOf != nil {
		return json.Marshal(&src.InitiateRemoteUpload201ResponseOneOf)
	}

	if src.Media != nil {
		return json.Marshal(&src.Media)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *InitiateRemoteUpload201Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.InitiateRemoteUpload201ResponseOneOf != nil {
		return obj.InitiateRemoteUpload201ResponseOneOf
	}

	if obj.Media != nil {
		return obj.Media
	}

	// all schemas are nil
	return nil
}

type NullableInitiateRemoteUpload201Response struct {
	value *InitiateRemoteUpload201Response
	isSet bool
}

func (v NullableInitiateRemoteUpload201Response) Get() *InitiateRemoteUpload201Response {
	return v.value
}

func (v *NullableInitiateRemoteUpload201Response) Set(val *InitiateRemoteUpload201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiateRemoteUpload201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiateRemoteUpload201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiateRemoteUpload201Response(val *InitiateRemoteUpload201Response) *NullableInitiateRemoteUpload201Response {
	return &NullableInitiateRemoteUpload201Response{value: val, isSet: true}
}

func (v NullableInitiateRemoteUpload201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiateRemoteUpload201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


