/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImagePrompt200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImagePrompt200Response{}

// ImagePrompt200Response struct for ImagePrompt200Response
type ImagePrompt200Response struct {
	Data ImagePromptResponse `json:"data"`
}

type _ImagePrompt200Response ImagePrompt200Response

// NewImagePrompt200Response instantiates a new ImagePrompt200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImagePrompt200Response(data ImagePromptResponse) *ImagePrompt200Response {
	this := ImagePrompt200Response{}
	this.Data = data
	return &this
}

// NewImagePrompt200ResponseWithDefaults instantiates a new ImagePrompt200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImagePrompt200ResponseWithDefaults() *ImagePrompt200Response {
	this := ImagePrompt200Response{}
	return &this
}

// GetData returns the Data field value
func (o *ImagePrompt200Response) GetData() ImagePromptResponse {
	if o == nil {
		var ret ImagePromptResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ImagePrompt200Response) GetDataOk() (*ImagePromptResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ImagePrompt200Response) SetData(v ImagePromptResponse) {
	o.Data = v
}

func (o ImagePrompt200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImagePrompt200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ImagePrompt200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImagePrompt200Response := _ImagePrompt200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImagePrompt200Response)

	if err != nil {
		return err
	}

	*o = ImagePrompt200Response(varImagePrompt200Response)

	return err
}

type NullableImagePrompt200Response struct {
	value *ImagePrompt200Response
	isSet bool
}

func (v NullableImagePrompt200Response) Get() *ImagePrompt200Response {
	return v.value
}

func (v *NullableImagePrompt200Response) Set(val *ImagePrompt200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableImagePrompt200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableImagePrompt200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImagePrompt200Response(val *ImagePrompt200Response) *NullableImagePrompt200Response {
	return &NullableImagePrompt200Response{value: val, isSet: true}
}

func (v NullableImagePrompt200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImagePrompt200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


