/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImageEditInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageEditInput{}

// ImageEditInput struct for ImageEditInput
type ImageEditInput struct {
	// UUID of the source media item to edit
	MediaUuid string `json:"media_uuid"`
	// Describe what to change in the image
	Prompt string `json:"prompt"`
	// UUID of a mask image. Transparent areas will be edited.
	MaskUuid *string `json:"mask_uuid,omitempty"`
	AspectRatio *string `json:"aspect_ratio,omitempty"`
	Count *int32 `json:"count,omitempty"`
	Quality *string `json:"quality,omitempty"`
}

type _ImageEditInput ImageEditInput

// NewImageEditInput instantiates a new ImageEditInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageEditInput(mediaUuid string, prompt string) *ImageEditInput {
	this := ImageEditInput{}
	this.MediaUuid = mediaUuid
	this.Prompt = prompt
	var aspectRatio string = "1:1"
	this.AspectRatio = &aspectRatio
	var count int32 = 1
	this.Count = &count
	var quality string = "standard"
	this.Quality = &quality
	return &this
}

// NewImageEditInputWithDefaults instantiates a new ImageEditInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageEditInputWithDefaults() *ImageEditInput {
	this := ImageEditInput{}
	var aspectRatio string = "1:1"
	this.AspectRatio = &aspectRatio
	var count int32 = 1
	this.Count = &count
	var quality string = "standard"
	this.Quality = &quality
	return &this
}

// GetMediaUuid returns the MediaUuid field value
func (o *ImageEditInput) GetMediaUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MediaUuid
}

// GetMediaUuidOk returns a tuple with the MediaUuid field value
// and a boolean to check if the value has been set.
func (o *ImageEditInput) GetMediaUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MediaUuid, true
}

// SetMediaUuid sets field value
func (o *ImageEditInput) SetMediaUuid(v string) {
	o.MediaUuid = v
}

// GetPrompt returns the Prompt field value
func (o *ImageEditInput) GetPrompt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value
// and a boolean to check if the value has been set.
func (o *ImageEditInput) GetPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prompt, true
}

// SetPrompt sets field value
func (o *ImageEditInput) SetPrompt(v string) {
	o.Prompt = v
}

// GetMaskUuid returns the MaskUuid field value if set, zero value otherwise.
func (o *ImageEditInput) GetMaskUuid() string {
	if o == nil || IsNil(o.MaskUuid) {
		var ret string
		return ret
	}
	return *o.MaskUuid
}

// GetMaskUuidOk returns a tuple with the MaskUuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageEditInput) GetMaskUuidOk() (*string, bool) {
	if o == nil || IsNil(o.MaskUuid) {
		return nil, false
	}
	return o.MaskUuid, true
}

// HasMaskUuid returns a boolean if a field has been set.
func (o *ImageEditInput) HasMaskUuid() bool {
	if o != nil && !IsNil(o.MaskUuid) {
		return true
	}

	return false
}

// SetMaskUuid gets a reference to the given string and assigns it to the MaskUuid field.
func (o *ImageEditInput) SetMaskUuid(v string) {
	o.MaskUuid = &v
}

// GetAspectRatio returns the AspectRatio field value if set, zero value otherwise.
func (o *ImageEditInput) GetAspectRatio() string {
	if o == nil || IsNil(o.AspectRatio) {
		var ret string
		return ret
	}
	return *o.AspectRatio
}

// GetAspectRatioOk returns a tuple with the AspectRatio field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageEditInput) GetAspectRatioOk() (*string, bool) {
	if o == nil || IsNil(o.AspectRatio) {
		return nil, false
	}
	return o.AspectRatio, true
}

// HasAspectRatio returns a boolean if a field has been set.
func (o *ImageEditInput) HasAspectRatio() bool {
	if o != nil && !IsNil(o.AspectRatio) {
		return true
	}

	return false
}

// SetAspectRatio gets a reference to the given string and assigns it to the AspectRatio field.
func (o *ImageEditInput) SetAspectRatio(v string) {
	o.AspectRatio = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *ImageEditInput) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageEditInput) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *ImageEditInput) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *ImageEditInput) SetCount(v int32) {
	o.Count = &v
}

// GetQuality returns the Quality field value if set, zero value otherwise.
func (o *ImageEditInput) GetQuality() string {
	if o == nil || IsNil(o.Quality) {
		var ret string
		return ret
	}
	return *o.Quality
}

// GetQualityOk returns a tuple with the Quality field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageEditInput) GetQualityOk() (*string, bool) {
	if o == nil || IsNil(o.Quality) {
		return nil, false
	}
	return o.Quality, true
}

// HasQuality returns a boolean if a field has been set.
func (o *ImageEditInput) HasQuality() bool {
	if o != nil && !IsNil(o.Quality) {
		return true
	}

	return false
}

// SetQuality gets a reference to the given string and assigns it to the Quality field.
func (o *ImageEditInput) SetQuality(v string) {
	o.Quality = &v
}

func (o ImageEditInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageEditInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["media_uuid"] = o.MediaUuid
	toSerialize["prompt"] = o.Prompt
	if !IsNil(o.MaskUuid) {
		toSerialize["mask_uuid"] = o.MaskUuid
	}
	if !IsNil(o.AspectRatio) {
		toSerialize["aspect_ratio"] = o.AspectRatio
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Quality) {
		toSerialize["quality"] = o.Quality
	}
	return toSerialize, nil
}

func (o *ImageEditInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"media_uuid",
		"prompt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImageEditInput := _ImageEditInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImageEditInput)

	if err != nil {
		return err
	}

	*o = ImageEditInput(varImageEditInput)

	return err
}

type NullableImageEditInput struct {
	value *ImageEditInput
	isSet bool
}

func (v NullableImageEditInput) Get() *ImageEditInput {
	return v.value
}

func (v *NullableImageEditInput) Set(val *ImageEditInput) {
	v.value = val
	v.isSet = true
}

func (v NullableImageEditInput) IsSet() bool {
	return v.isSet
}

func (v *NullableImageEditInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageEditInput(val *ImageEditInput) *NullableImageEditInput {
	return &NullableImageEditInput{value: val, isSet: true}
}

func (v NullableImageEditInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageEditInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


