/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CheckoutSubscriptionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckoutSubscriptionRequest{}

// CheckoutSubscriptionRequest struct for CheckoutSubscriptionRequest
type CheckoutSubscriptionRequest struct {
	PlanId int32 `json:"plan_id"`
	Cycle string `json:"cycle"`
	Coupon *string `json:"coupon,omitempty"`
}

type _CheckoutSubscriptionRequest CheckoutSubscriptionRequest

// NewCheckoutSubscriptionRequest instantiates a new CheckoutSubscriptionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckoutSubscriptionRequest(planId int32, cycle string) *CheckoutSubscriptionRequest {
	this := CheckoutSubscriptionRequest{}
	this.PlanId = planId
	this.Cycle = cycle
	return &this
}

// NewCheckoutSubscriptionRequestWithDefaults instantiates a new CheckoutSubscriptionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckoutSubscriptionRequestWithDefaults() *CheckoutSubscriptionRequest {
	this := CheckoutSubscriptionRequest{}
	return &this
}

// GetPlanId returns the PlanId field value
func (o *CheckoutSubscriptionRequest) GetPlanId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value
// and a boolean to check if the value has been set.
func (o *CheckoutSubscriptionRequest) GetPlanIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanId, true
}

// SetPlanId sets field value
func (o *CheckoutSubscriptionRequest) SetPlanId(v int32) {
	o.PlanId = v
}

// GetCycle returns the Cycle field value
func (o *CheckoutSubscriptionRequest) GetCycle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cycle
}

// GetCycleOk returns a tuple with the Cycle field value
// and a boolean to check if the value has been set.
func (o *CheckoutSubscriptionRequest) GetCycleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cycle, true
}

// SetCycle sets field value
func (o *CheckoutSubscriptionRequest) SetCycle(v string) {
	o.Cycle = v
}

// GetCoupon returns the Coupon field value if set, zero value otherwise.
func (o *CheckoutSubscriptionRequest) GetCoupon() string {
	if o == nil || IsNil(o.Coupon) {
		var ret string
		return ret
	}
	return *o.Coupon
}

// GetCouponOk returns a tuple with the Coupon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckoutSubscriptionRequest) GetCouponOk() (*string, bool) {
	if o == nil || IsNil(o.Coupon) {
		return nil, false
	}
	return o.Coupon, true
}

// HasCoupon returns a boolean if a field has been set.
func (o *CheckoutSubscriptionRequest) HasCoupon() bool {
	if o != nil && !IsNil(o.Coupon) {
		return true
	}

	return false
}

// SetCoupon gets a reference to the given string and assigns it to the Coupon field.
func (o *CheckoutSubscriptionRequest) SetCoupon(v string) {
	o.Coupon = &v
}

func (o CheckoutSubscriptionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckoutSubscriptionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plan_id"] = o.PlanId
	toSerialize["cycle"] = o.Cycle
	if !IsNil(o.Coupon) {
		toSerialize["coupon"] = o.Coupon
	}
	return toSerialize, nil
}

func (o *CheckoutSubscriptionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plan_id",
		"cycle",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCheckoutSubscriptionRequest := _CheckoutSubscriptionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCheckoutSubscriptionRequest)

	if err != nil {
		return err
	}

	*o = CheckoutSubscriptionRequest(varCheckoutSubscriptionRequest)

	return err
}

type NullableCheckoutSubscriptionRequest struct {
	value *CheckoutSubscriptionRequest
	isSet bool
}

func (v NullableCheckoutSubscriptionRequest) Get() *CheckoutSubscriptionRequest {
	return v.value
}

func (v *NullableCheckoutSubscriptionRequest) Set(val *CheckoutSubscriptionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckoutSubscriptionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckoutSubscriptionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckoutSubscriptionRequest(val *CheckoutSubscriptionRequest) *NullableCheckoutSubscriptionRequest {
	return &NullableCheckoutSubscriptionRequest{value: val, isSet: true}
}

func (v NullableCheckoutSubscriptionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckoutSubscriptionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


