/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
)

// checks if the ImageGenerate429Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageGenerate429Response{}

// ImageGenerate429Response struct for ImageGenerate429Response
type ImageGenerate429Response struct {
	Message *string `json:"message,omitempty"`
}

// NewImageGenerate429Response instantiates a new ImageGenerate429Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageGenerate429Response() *ImageGenerate429Response {
	this := ImageGenerate429Response{}
	return &this
}

// NewImageGenerate429ResponseWithDefaults instantiates a new ImageGenerate429Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageGenerate429ResponseWithDefaults() *ImageGenerate429Response {
	this := ImageGenerate429Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ImageGenerate429Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageGenerate429Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ImageGenerate429Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ImageGenerate429Response) SetMessage(v string) {
	o.Message = &v
}

func (o ImageGenerate429Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageGenerate429Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableImageGenerate429Response struct {
	value *ImageGenerate429Response
	isSet bool
}

func (v NullableImageGenerate429Response) Get() *ImageGenerate429Response {
	return v.value
}

func (v *NullableImageGenerate429Response) Set(val *ImageGenerate429Response) {
	v.value = val
	v.isSet = true
}

func (v NullableImageGenerate429Response) IsSet() bool {
	return v.isSet
}

func (v *NullableImageGenerate429Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageGenerate429Response(val *ImageGenerate429Response) *NullableImageGenerate429Response {
	return &NullableImageGenerate429Response{value: val, isSet: true}
}

func (v NullableImageGenerate429Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageGenerate429Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


