/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReceiptInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReceiptInput{}

// ReceiptInput struct for ReceiptInput
type ReceiptInput struct {
	WorkspaceUuid string `json:"workspace_uuid"`
	TransactionId string `json:"transaction_id"`
	InvoiceNumber string `json:"invoice_number"`
	Amount float32 `json:"amount"`
	Tax float32 `json:"tax"`
	Currency string `json:"currency"`
	Description *string `json:"description,omitempty"`
	ReceiptUrl *string `json:"receipt_url,omitempty"`
	PaidAt string `json:"paid_at"`
}

type _ReceiptInput ReceiptInput

// NewReceiptInput instantiates a new ReceiptInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceiptInput(workspaceUuid string, transactionId string, invoiceNumber string, amount float32, tax float32, currency string, paidAt string) *ReceiptInput {
	this := ReceiptInput{}
	this.WorkspaceUuid = workspaceUuid
	this.TransactionId = transactionId
	this.InvoiceNumber = invoiceNumber
	this.Amount = amount
	this.Tax = tax
	this.Currency = currency
	this.PaidAt = paidAt
	return &this
}

// NewReceiptInputWithDefaults instantiates a new ReceiptInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceiptInputWithDefaults() *ReceiptInput {
	this := ReceiptInput{}
	return &this
}

// GetWorkspaceUuid returns the WorkspaceUuid field value
func (o *ReceiptInput) GetWorkspaceUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceUuid
}

// GetWorkspaceUuidOk returns a tuple with the WorkspaceUuid field value
// and a boolean to check if the value has been set.
func (o *ReceiptInput) GetWorkspaceUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceUuid, true
}

// SetWorkspaceUuid sets field value
func (o *ReceiptInput) SetWorkspaceUuid(v string) {
	o.WorkspaceUuid = v
}

// GetTransactionId returns the TransactionId field value
func (o *ReceiptInput) GetTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value
// and a boolean to check if the value has been set.
func (o *ReceiptInput) GetTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionId, true
}

// SetTransactionId sets field value
func (o *ReceiptInput) SetTransactionId(v string) {
	o.TransactionId = v
}

// GetInvoiceNumber returns the InvoiceNumber field value
func (o *ReceiptInput) GetInvoiceNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InvoiceNumber
}

// GetInvoiceNumberOk returns a tuple with the InvoiceNumber field value
// and a boolean to check if the value has been set.
func (o *ReceiptInput) GetInvoiceNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvoiceNumber, true
}

// SetInvoiceNumber sets field value
func (o *ReceiptInput) SetInvoiceNumber(v string) {
	o.InvoiceNumber = v
}

// GetAmount returns the Amount field value
func (o *ReceiptInput) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *ReceiptInput) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *ReceiptInput) SetAmount(v float32) {
	o.Amount = v
}

// GetTax returns the Tax field value
func (o *ReceiptInput) GetTax() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Tax
}

// GetTaxOk returns a tuple with the Tax field value
// and a boolean to check if the value has been set.
func (o *ReceiptInput) GetTaxOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tax, true
}

// SetTax sets field value
func (o *ReceiptInput) SetTax(v float32) {
	o.Tax = v
}

// GetCurrency returns the Currency field value
func (o *ReceiptInput) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *ReceiptInput) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *ReceiptInput) SetCurrency(v string) {
	o.Currency = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ReceiptInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReceiptInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ReceiptInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ReceiptInput) SetDescription(v string) {
	o.Description = &v
}

// GetReceiptUrl returns the ReceiptUrl field value if set, zero value otherwise.
func (o *ReceiptInput) GetReceiptUrl() string {
	if o == nil || IsNil(o.ReceiptUrl) {
		var ret string
		return ret
	}
	return *o.ReceiptUrl
}

// GetReceiptUrlOk returns a tuple with the ReceiptUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReceiptInput) GetReceiptUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ReceiptUrl) {
		return nil, false
	}
	return o.ReceiptUrl, true
}

// HasReceiptUrl returns a boolean if a field has been set.
func (o *ReceiptInput) HasReceiptUrl() bool {
	if o != nil && !IsNil(o.ReceiptUrl) {
		return true
	}

	return false
}

// SetReceiptUrl gets a reference to the given string and assigns it to the ReceiptUrl field.
func (o *ReceiptInput) SetReceiptUrl(v string) {
	o.ReceiptUrl = &v
}

// GetPaidAt returns the PaidAt field value
func (o *ReceiptInput) GetPaidAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaidAt
}

// GetPaidAtOk returns a tuple with the PaidAt field value
// and a boolean to check if the value has been set.
func (o *ReceiptInput) GetPaidAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaidAt, true
}

// SetPaidAt sets field value
func (o *ReceiptInput) SetPaidAt(v string) {
	o.PaidAt = v
}

func (o ReceiptInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReceiptInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["workspace_uuid"] = o.WorkspaceUuid
	toSerialize["transaction_id"] = o.TransactionId
	toSerialize["invoice_number"] = o.InvoiceNumber
	toSerialize["amount"] = o.Amount
	toSerialize["tax"] = o.Tax
	toSerialize["currency"] = o.Currency
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ReceiptUrl) {
		toSerialize["receipt_url"] = o.ReceiptUrl
	}
	toSerialize["paid_at"] = o.PaidAt
	return toSerialize, nil
}

func (o *ReceiptInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"workspace_uuid",
		"transaction_id",
		"invoice_number",
		"amount",
		"tax",
		"currency",
		"paid_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReceiptInput := _ReceiptInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReceiptInput)

	if err != nil {
		return err
	}

	*o = ReceiptInput(varReceiptInput)

	return err
}

type NullableReceiptInput struct {
	value *ReceiptInput
	isSet bool
}

func (v NullableReceiptInput) Get() *ReceiptInput {
	return v.value
}

func (v *NullableReceiptInput) Set(val *ReceiptInput) {
	v.value = val
	v.isSet = true
}

func (v NullableReceiptInput) IsSet() bool {
	return v.isSet
}

func (v *NullableReceiptInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceiptInput(val *ReceiptInput) *NullableReceiptInput {
	return &NullableReceiptInput{value: val, isSet: true}
}

func (v NullableReceiptInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceiptInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


