/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostVersion{}

// PostVersion struct for PostVersion
type PostVersion struct {
	// Use `0` for the original/default version.
	AccountId int32 `json:"account_id"`
	// Must be `true` for the first version.
	IsOriginal bool `json:"is_original"`
	Content []PostContent `json:"content"`
	// Platform-specific publishing options.
	Options map[string]interface{} `json:"options,omitempty"`
}

type _PostVersion PostVersion

// NewPostVersion instantiates a new PostVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostVersion(accountId int32, isOriginal bool, content []PostContent) *PostVersion {
	this := PostVersion{}
	this.AccountId = accountId
	this.IsOriginal = isOriginal
	this.Content = content
	return &this
}

// NewPostVersionWithDefaults instantiates a new PostVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostVersionWithDefaults() *PostVersion {
	this := PostVersion{}
	return &this
}

// GetAccountId returns the AccountId field value
func (o *PostVersion) GetAccountId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value
// and a boolean to check if the value has been set.
func (o *PostVersion) GetAccountIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountId, true
}

// SetAccountId sets field value
func (o *PostVersion) SetAccountId(v int32) {
	o.AccountId = v
}

// GetIsOriginal returns the IsOriginal field value
func (o *PostVersion) GetIsOriginal() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsOriginal
}

// GetIsOriginalOk returns a tuple with the IsOriginal field value
// and a boolean to check if the value has been set.
func (o *PostVersion) GetIsOriginalOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsOriginal, true
}

// SetIsOriginal sets field value
func (o *PostVersion) SetIsOriginal(v bool) {
	o.IsOriginal = v
}

// GetContent returns the Content field value
func (o *PostVersion) GetContent() []PostContent {
	if o == nil {
		var ret []PostContent
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *PostVersion) GetContentOk() ([]PostContent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Content, true
}

// SetContent sets field value
func (o *PostVersion) SetContent(v []PostContent) {
	o.Content = v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *PostVersion) GetOptions() map[string]interface{} {
	if o == nil || IsNil(o.Options) {
		var ret map[string]interface{}
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostVersion) GetOptionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Options) {
		return map[string]interface{}{}, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *PostVersion) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given map[string]interface{} and assigns it to the Options field.
func (o *PostVersion) SetOptions(v map[string]interface{}) {
	o.Options = v
}

func (o PostVersion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account_id"] = o.AccountId
	toSerialize["is_original"] = o.IsOriginal
	toSerialize["content"] = o.Content
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

func (o *PostVersion) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account_id",
		"is_original",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostVersion := _PostVersion{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostVersion)

	if err != nil {
		return err
	}

	*o = PostVersion(varPostVersion)

	return err
}

type NullablePostVersion struct {
	value *PostVersion
	isSet bool
}

func (v NullablePostVersion) Get() *PostVersion {
	return v.value
}

func (v *NullablePostVersion) Set(val *PostVersion) {
	v.value = val
	v.isSet = true
}

func (v NullablePostVersion) IsSet() bool {
	return v.isSet
}

func (v *NullablePostVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostVersion(val *PostVersion) *NullablePostVersion {
	return &NullablePostVersion{value: val, isSet: true}
}

func (v NullablePostVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


