/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImagePromptResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImagePromptResponse{}

// ImagePromptResponse struct for ImagePromptResponse
type ImagePromptResponse struct {
	Prompt string `json:"prompt"`
}

type _ImagePromptResponse ImagePromptResponse

// NewImagePromptResponse instantiates a new ImagePromptResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImagePromptResponse(prompt string) *ImagePromptResponse {
	this := ImagePromptResponse{}
	this.Prompt = prompt
	return &this
}

// NewImagePromptResponseWithDefaults instantiates a new ImagePromptResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImagePromptResponseWithDefaults() *ImagePromptResponse {
	this := ImagePromptResponse{}
	return &this
}

// GetPrompt returns the Prompt field value
func (o *ImagePromptResponse) GetPrompt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value
// and a boolean to check if the value has been set.
func (o *ImagePromptResponse) GetPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prompt, true
}

// SetPrompt sets field value
func (o *ImagePromptResponse) SetPrompt(v string) {
	o.Prompt = v
}

func (o ImagePromptResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImagePromptResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["prompt"] = o.Prompt
	return toSerialize, nil
}

func (o *ImagePromptResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"prompt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImagePromptResponse := _ImagePromptResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImagePromptResponse)

	if err != nil {
		return err
	}

	*o = ImagePromptResponse(varImagePromptResponse)

	return err
}

type NullableImagePromptResponse struct {
	value *ImagePromptResponse
	isSet bool
}

func (v NullableImagePromptResponse) Get() *ImagePromptResponse {
	return v.value
}

func (v *NullableImagePromptResponse) Set(val *ImagePromptResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableImagePromptResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableImagePromptResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImagePromptResponse(val *ImagePromptResponse) *NullableImagePromptResponse {
	return &NullableImagePromptResponse{value: val, isSet: true}
}

func (v NullableImagePromptResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImagePromptResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


