/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
)

// checks if the GetRemoteUploadStatus200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRemoteUploadStatus200Response{}

// GetRemoteUploadStatus200Response struct for GetRemoteUploadStatus200Response
type GetRemoteUploadStatus200Response struct {
	Status *string `json:"status,omitempty"`
	// Present when status is complete.
	Media *Media `json:"media,omitempty"`
}

// NewGetRemoteUploadStatus200Response instantiates a new GetRemoteUploadStatus200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRemoteUploadStatus200Response() *GetRemoteUploadStatus200Response {
	this := GetRemoteUploadStatus200Response{}
	return &this
}

// NewGetRemoteUploadStatus200ResponseWithDefaults instantiates a new GetRemoteUploadStatus200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRemoteUploadStatus200ResponseWithDefaults() *GetRemoteUploadStatus200Response {
	this := GetRemoteUploadStatus200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetRemoteUploadStatus200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRemoteUploadStatus200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetRemoteUploadStatus200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetRemoteUploadStatus200Response) SetStatus(v string) {
	o.Status = &v
}

// GetMedia returns the Media field value if set, zero value otherwise.
func (o *GetRemoteUploadStatus200Response) GetMedia() Media {
	if o == nil || IsNil(o.Media) {
		var ret Media
		return ret
	}
	return *o.Media
}

// GetMediaOk returns a tuple with the Media field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRemoteUploadStatus200Response) GetMediaOk() (*Media, bool) {
	if o == nil || IsNil(o.Media) {
		return nil, false
	}
	return o.Media, true
}

// HasMedia returns a boolean if a field has been set.
func (o *GetRemoteUploadStatus200Response) HasMedia() bool {
	if o != nil && !IsNil(o.Media) {
		return true
	}

	return false
}

// SetMedia gets a reference to the given Media and assigns it to the Media field.
func (o *GetRemoteUploadStatus200Response) SetMedia(v Media) {
	o.Media = &v
}

func (o GetRemoteUploadStatus200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRemoteUploadStatus200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Media) {
		toSerialize["media"] = o.Media
	}
	return toSerialize, nil
}

type NullableGetRemoteUploadStatus200Response struct {
	value *GetRemoteUploadStatus200Response
	isSet bool
}

func (v NullableGetRemoteUploadStatus200Response) Get() *GetRemoteUploadStatus200Response {
	return v.value
}

func (v *NullableGetRemoteUploadStatus200Response) Set(val *GetRemoteUploadStatus200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRemoteUploadStatus200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRemoteUploadStatus200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRemoteUploadStatus200Response(val *GetRemoteUploadStatus200Response) *NullableGetRemoteUploadStatus200Response {
	return &NullableGetRemoteUploadStatus200Response{value: val, isSet: true}
}

func (v NullableGetRemoteUploadStatus200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRemoteUploadStatus200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


