/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteWorkspacesBulkRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteWorkspacesBulkRequest{}

// DeleteWorkspacesBulkRequest struct for DeleteWorkspacesBulkRequest
type DeleteWorkspacesBulkRequest struct {
	Workspaces []string `json:"workspaces"`
}

type _DeleteWorkspacesBulkRequest DeleteWorkspacesBulkRequest

// NewDeleteWorkspacesBulkRequest instantiates a new DeleteWorkspacesBulkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteWorkspacesBulkRequest(workspaces []string) *DeleteWorkspacesBulkRequest {
	this := DeleteWorkspacesBulkRequest{}
	this.Workspaces = workspaces
	return &this
}

// NewDeleteWorkspacesBulkRequestWithDefaults instantiates a new DeleteWorkspacesBulkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteWorkspacesBulkRequestWithDefaults() *DeleteWorkspacesBulkRequest {
	this := DeleteWorkspacesBulkRequest{}
	return &this
}

// GetWorkspaces returns the Workspaces field value
func (o *DeleteWorkspacesBulkRequest) GetWorkspaces() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Workspaces
}

// GetWorkspacesOk returns a tuple with the Workspaces field value
// and a boolean to check if the value has been set.
func (o *DeleteWorkspacesBulkRequest) GetWorkspacesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Workspaces, true
}

// SetWorkspaces sets field value
func (o *DeleteWorkspacesBulkRequest) SetWorkspaces(v []string) {
	o.Workspaces = v
}

func (o DeleteWorkspacesBulkRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteWorkspacesBulkRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["workspaces"] = o.Workspaces
	return toSerialize, nil
}

func (o *DeleteWorkspacesBulkRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"workspaces",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteWorkspacesBulkRequest := _DeleteWorkspacesBulkRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteWorkspacesBulkRequest)

	if err != nil {
		return err
	}

	*o = DeleteWorkspacesBulkRequest(varDeleteWorkspacesBulkRequest)

	return err
}

type NullableDeleteWorkspacesBulkRequest struct {
	value *DeleteWorkspacesBulkRequest
	isSet bool
}

func (v NullableDeleteWorkspacesBulkRequest) Get() *DeleteWorkspacesBulkRequest {
	return v.value
}

func (v *NullableDeleteWorkspacesBulkRequest) Set(val *DeleteWorkspacesBulkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteWorkspacesBulkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteWorkspacesBulkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteWorkspacesBulkRequest(val *DeleteWorkspacesBulkRequest) *NullableDeleteWorkspacesBulkRequest {
	return &NullableDeleteWorkspacesBulkRequest{value: val, isSet: true}
}

func (v NullableDeleteWorkspacesBulkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteWorkspacesBulkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


