/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImageAltTextResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageAltTextResponse{}

// ImageAltTextResponse struct for ImageAltTextResponse
type ImageAltTextResponse struct {
	MediaUuid string `json:"media_uuid"`
	AltText string `json:"alt_text"`
	CreditsUsed int32 `json:"credits_used"`
	CreditsRemaining *int32 `json:"credits_remaining,omitempty"`
}

type _ImageAltTextResponse ImageAltTextResponse

// NewImageAltTextResponse instantiates a new ImageAltTextResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageAltTextResponse(mediaUuid string, altText string, creditsUsed int32) *ImageAltTextResponse {
	this := ImageAltTextResponse{}
	this.MediaUuid = mediaUuid
	this.AltText = altText
	this.CreditsUsed = creditsUsed
	return &this
}

// NewImageAltTextResponseWithDefaults instantiates a new ImageAltTextResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageAltTextResponseWithDefaults() *ImageAltTextResponse {
	this := ImageAltTextResponse{}
	return &this
}

// GetMediaUuid returns the MediaUuid field value
func (o *ImageAltTextResponse) GetMediaUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MediaUuid
}

// GetMediaUuidOk returns a tuple with the MediaUuid field value
// and a boolean to check if the value has been set.
func (o *ImageAltTextResponse) GetMediaUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MediaUuid, true
}

// SetMediaUuid sets field value
func (o *ImageAltTextResponse) SetMediaUuid(v string) {
	o.MediaUuid = v
}

// GetAltText returns the AltText field value
func (o *ImageAltTextResponse) GetAltText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AltText
}

// GetAltTextOk returns a tuple with the AltText field value
// and a boolean to check if the value has been set.
func (o *ImageAltTextResponse) GetAltTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AltText, true
}

// SetAltText sets field value
func (o *ImageAltTextResponse) SetAltText(v string) {
	o.AltText = v
}

// GetCreditsUsed returns the CreditsUsed field value
func (o *ImageAltTextResponse) GetCreditsUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreditsUsed
}

// GetCreditsUsedOk returns a tuple with the CreditsUsed field value
// and a boolean to check if the value has been set.
func (o *ImageAltTextResponse) GetCreditsUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsUsed, true
}

// SetCreditsUsed sets field value
func (o *ImageAltTextResponse) SetCreditsUsed(v int32) {
	o.CreditsUsed = v
}

// GetCreditsRemaining returns the CreditsRemaining field value if set, zero value otherwise.
func (o *ImageAltTextResponse) GetCreditsRemaining() int32 {
	if o == nil || IsNil(o.CreditsRemaining) {
		var ret int32
		return ret
	}
	return *o.CreditsRemaining
}

// GetCreditsRemainingOk returns a tuple with the CreditsRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageAltTextResponse) GetCreditsRemainingOk() (*int32, bool) {
	if o == nil || IsNil(o.CreditsRemaining) {
		return nil, false
	}
	return o.CreditsRemaining, true
}

// HasCreditsRemaining returns a boolean if a field has been set.
func (o *ImageAltTextResponse) HasCreditsRemaining() bool {
	if o != nil && !IsNil(o.CreditsRemaining) {
		return true
	}

	return false
}

// SetCreditsRemaining gets a reference to the given int32 and assigns it to the CreditsRemaining field.
func (o *ImageAltTextResponse) SetCreditsRemaining(v int32) {
	o.CreditsRemaining = &v
}

func (o ImageAltTextResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageAltTextResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["media_uuid"] = o.MediaUuid
	toSerialize["alt_text"] = o.AltText
	toSerialize["credits_used"] = o.CreditsUsed
	if !IsNil(o.CreditsRemaining) {
		toSerialize["credits_remaining"] = o.CreditsRemaining
	}
	return toSerialize, nil
}

func (o *ImageAltTextResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"media_uuid",
		"alt_text",
		"credits_used",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImageAltTextResponse := _ImageAltTextResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImageAltTextResponse)

	if err != nil {
		return err
	}

	*o = ImageAltTextResponse(varImageAltTextResponse)

	return err
}

type NullableImageAltTextResponse struct {
	value *ImageAltTextResponse
	isSet bool
}

func (v NullableImageAltTextResponse) Get() *ImageAltTextResponse {
	return v.value
}

func (v *NullableImageAltTextResponse) Set(val *ImageAltTextResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableImageAltTextResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableImageAltTextResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageAltTextResponse(val *ImageAltTextResponse) *NullableImageAltTextResponse {
	return &NullableImageAltTextResponse{value: val, isSet: true}
}

func (v NullableImageAltTextResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageAltTextResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


