/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImageVariationsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageVariationsResponse{}

// ImageVariationsResponse struct for ImageVariationsResponse
type ImageVariationsResponse struct {
	Images []Media `json:"images"`
	AspectRatio string `json:"aspect_ratio"`
	Quality string `json:"quality"`
	CreditsUsed int32 `json:"credits_used"`
	CreditsRemaining *int32 `json:"credits_remaining,omitempty"`
}

type _ImageVariationsResponse ImageVariationsResponse

// NewImageVariationsResponse instantiates a new ImageVariationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageVariationsResponse(images []Media, aspectRatio string, quality string, creditsUsed int32) *ImageVariationsResponse {
	this := ImageVariationsResponse{}
	this.Images = images
	this.AspectRatio = aspectRatio
	this.Quality = quality
	this.CreditsUsed = creditsUsed
	return &this
}

// NewImageVariationsResponseWithDefaults instantiates a new ImageVariationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageVariationsResponseWithDefaults() *ImageVariationsResponse {
	this := ImageVariationsResponse{}
	return &this
}

// GetImages returns the Images field value
func (o *ImageVariationsResponse) GetImages() []Media {
	if o == nil {
		var ret []Media
		return ret
	}

	return o.Images
}

// GetImagesOk returns a tuple with the Images field value
// and a boolean to check if the value has been set.
func (o *ImageVariationsResponse) GetImagesOk() ([]Media, bool) {
	if o == nil {
		return nil, false
	}
	return o.Images, true
}

// SetImages sets field value
func (o *ImageVariationsResponse) SetImages(v []Media) {
	o.Images = v
}

// GetAspectRatio returns the AspectRatio field value
func (o *ImageVariationsResponse) GetAspectRatio() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AspectRatio
}

// GetAspectRatioOk returns a tuple with the AspectRatio field value
// and a boolean to check if the value has been set.
func (o *ImageVariationsResponse) GetAspectRatioOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AspectRatio, true
}

// SetAspectRatio sets field value
func (o *ImageVariationsResponse) SetAspectRatio(v string) {
	o.AspectRatio = v
}

// GetQuality returns the Quality field value
func (o *ImageVariationsResponse) GetQuality() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Quality
}

// GetQualityOk returns a tuple with the Quality field value
// and a boolean to check if the value has been set.
func (o *ImageVariationsResponse) GetQualityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quality, true
}

// SetQuality sets field value
func (o *ImageVariationsResponse) SetQuality(v string) {
	o.Quality = v
}

// GetCreditsUsed returns the CreditsUsed field value
func (o *ImageVariationsResponse) GetCreditsUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreditsUsed
}

// GetCreditsUsedOk returns a tuple with the CreditsUsed field value
// and a boolean to check if the value has been set.
func (o *ImageVariationsResponse) GetCreditsUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsUsed, true
}

// SetCreditsUsed sets field value
func (o *ImageVariationsResponse) SetCreditsUsed(v int32) {
	o.CreditsUsed = v
}

// GetCreditsRemaining returns the CreditsRemaining field value if set, zero value otherwise.
func (o *ImageVariationsResponse) GetCreditsRemaining() int32 {
	if o == nil || IsNil(o.CreditsRemaining) {
		var ret int32
		return ret
	}
	return *o.CreditsRemaining
}

// GetCreditsRemainingOk returns a tuple with the CreditsRemaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageVariationsResponse) GetCreditsRemainingOk() (*int32, bool) {
	if o == nil || IsNil(o.CreditsRemaining) {
		return nil, false
	}
	return o.CreditsRemaining, true
}

// HasCreditsRemaining returns a boolean if a field has been set.
func (o *ImageVariationsResponse) HasCreditsRemaining() bool {
	if o != nil && !IsNil(o.CreditsRemaining) {
		return true
	}

	return false
}

// SetCreditsRemaining gets a reference to the given int32 and assigns it to the CreditsRemaining field.
func (o *ImageVariationsResponse) SetCreditsRemaining(v int32) {
	o.CreditsRemaining = &v
}

func (o ImageVariationsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageVariationsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["images"] = o.Images
	toSerialize["aspect_ratio"] = o.AspectRatio
	toSerialize["quality"] = o.Quality
	toSerialize["credits_used"] = o.CreditsUsed
	if !IsNil(o.CreditsRemaining) {
		toSerialize["credits_remaining"] = o.CreditsRemaining
	}
	return toSerialize, nil
}

func (o *ImageVariationsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"images",
		"aspect_ratio",
		"quality",
		"credits_used",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImageVariationsResponse := _ImageVariationsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImageVariationsResponse)

	if err != nil {
		return err
	}

	*o = ImageVariationsResponse(varImageVariationsResponse)

	return err
}

type NullableImageVariationsResponse struct {
	value *ImageVariationsResponse
	isSet bool
}

func (v NullableImageVariationsResponse) Get() *ImageVariationsResponse {
	return v.value
}

func (v *NullableImageVariationsResponse) Set(val *ImageVariationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableImageVariationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableImageVariationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageVariationsResponse(val *ImageVariationsResponse) *NullableImageVariationsResponse {
	return &NullableImageVariationsResponse{value: val, isSet: true}
}

func (v NullableImageVariationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageVariationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


