/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
)

// checks if the InitiateRemoteUpload200ResponseOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InitiateRemoteUpload200ResponseOneOf{}

// InitiateRemoteUpload200ResponseOneOf struct for InitiateRemoteUpload200ResponseOneOf
type InitiateRemoteUpload200ResponseOneOf struct {
	DownloadId *string `json:"download_id,omitempty"`
}

// NewInitiateRemoteUpload200ResponseOneOf instantiates a new InitiateRemoteUpload200ResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiateRemoteUpload200ResponseOneOf() *InitiateRemoteUpload200ResponseOneOf {
	this := InitiateRemoteUpload200ResponseOneOf{}
	return &this
}

// NewInitiateRemoteUpload200ResponseOneOfWithDefaults instantiates a new InitiateRemoteUpload200ResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiateRemoteUpload200ResponseOneOfWithDefaults() *InitiateRemoteUpload200ResponseOneOf {
	this := InitiateRemoteUpload200ResponseOneOf{}
	return &this
}

// GetDownloadId returns the DownloadId field value if set, zero value otherwise.
func (o *InitiateRemoteUpload200ResponseOneOf) GetDownloadId() string {
	if o == nil || IsNil(o.DownloadId) {
		var ret string
		return ret
	}
	return *o.DownloadId
}

// GetDownloadIdOk returns a tuple with the DownloadId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiateRemoteUpload200ResponseOneOf) GetDownloadIdOk() (*string, bool) {
	if o == nil || IsNil(o.DownloadId) {
		return nil, false
	}
	return o.DownloadId, true
}

// HasDownloadId returns a boolean if a field has been set.
func (o *InitiateRemoteUpload200ResponseOneOf) HasDownloadId() bool {
	if o != nil && !IsNil(o.DownloadId) {
		return true
	}

	return false
}

// SetDownloadId gets a reference to the given string and assigns it to the DownloadId field.
func (o *InitiateRemoteUpload200ResponseOneOf) SetDownloadId(v string) {
	o.DownloadId = &v
}

func (o InitiateRemoteUpload200ResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitiateRemoteUpload200ResponseOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DownloadId) {
		toSerialize["download_id"] = o.DownloadId
	}
	return toSerialize, nil
}

type NullableInitiateRemoteUpload200ResponseOneOf struct {
	value *InitiateRemoteUpload200ResponseOneOf
	isSet bool
}

func (v NullableInitiateRemoteUpload200ResponseOneOf) Get() *InitiateRemoteUpload200ResponseOneOf {
	return v.value
}

func (v *NullableInitiateRemoteUpload200ResponseOneOf) Set(val *InitiateRemoteUpload200ResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiateRemoteUpload200ResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiateRemoteUpload200ResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiateRemoteUpload200ResponseOneOf(val *InitiateRemoteUpload200ResponseOneOf) *NullableInitiateRemoteUpload200ResponseOneOf {
	return &NullableInitiateRemoteUpload200ResponseOneOf{value: val, isSet: true}
}

func (v NullableInitiateRemoteUpload200ResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiateRemoteUpload200ResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


