/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WorkspaceInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspaceInput{}

// WorkspaceInput struct for WorkspaceInput
type WorkspaceInput struct {
	Name string `json:"name"`
	HexColor string `json:"hex_color"`
	OwnerId *int32 `json:"owner_id,omitempty"`
	AccessStatus string `json:"access_status"`
}

type _WorkspaceInput WorkspaceInput

// NewWorkspaceInput instantiates a new WorkspaceInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceInput(name string, hexColor string, accessStatus string) *WorkspaceInput {
	this := WorkspaceInput{}
	this.Name = name
	this.HexColor = hexColor
	this.AccessStatus = accessStatus
	return &this
}

// NewWorkspaceInputWithDefaults instantiates a new WorkspaceInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceInputWithDefaults() *WorkspaceInput {
	this := WorkspaceInput{}
	return &this
}

// GetName returns the Name field value
func (o *WorkspaceInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WorkspaceInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *WorkspaceInput) SetName(v string) {
	o.Name = v
}

// GetHexColor returns the HexColor field value
func (o *WorkspaceInput) GetHexColor() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HexColor
}

// GetHexColorOk returns a tuple with the HexColor field value
// and a boolean to check if the value has been set.
func (o *WorkspaceInput) GetHexColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HexColor, true
}

// SetHexColor sets field value
func (o *WorkspaceInput) SetHexColor(v string) {
	o.HexColor = v
}

// GetOwnerId returns the OwnerId field value if set, zero value otherwise.
func (o *WorkspaceInput) GetOwnerId() int32 {
	if o == nil || IsNil(o.OwnerId) {
		var ret int32
		return ret
	}
	return *o.OwnerId
}

// GetOwnerIdOk returns a tuple with the OwnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceInput) GetOwnerIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OwnerId) {
		return nil, false
	}
	return o.OwnerId, true
}

// HasOwnerId returns a boolean if a field has been set.
func (o *WorkspaceInput) HasOwnerId() bool {
	if o != nil && !IsNil(o.OwnerId) {
		return true
	}

	return false
}

// SetOwnerId gets a reference to the given int32 and assigns it to the OwnerId field.
func (o *WorkspaceInput) SetOwnerId(v int32) {
	o.OwnerId = &v
}

// GetAccessStatus returns the AccessStatus field value
func (o *WorkspaceInput) GetAccessStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessStatus
}

// GetAccessStatusOk returns a tuple with the AccessStatus field value
// and a boolean to check if the value has been set.
func (o *WorkspaceInput) GetAccessStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessStatus, true
}

// SetAccessStatus sets field value
func (o *WorkspaceInput) SetAccessStatus(v string) {
	o.AccessStatus = v
}

func (o WorkspaceInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspaceInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["hex_color"] = o.HexColor
	if !IsNil(o.OwnerId) {
		toSerialize["owner_id"] = o.OwnerId
	}
	toSerialize["access_status"] = o.AccessStatus
	return toSerialize, nil
}

func (o *WorkspaceInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"hex_color",
		"access_status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkspaceInput := _WorkspaceInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkspaceInput)

	if err != nil {
		return err
	}

	*o = WorkspaceInput(varWorkspaceInput)

	return err
}

type NullableWorkspaceInput struct {
	value *WorkspaceInput
	isSet bool
}

func (v NullableWorkspaceInput) Get() *WorkspaceInput {
	return v.value
}

func (v *NullableWorkspaceInput) Set(val *WorkspaceInput) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceInput) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceInput(val *WorkspaceInput) *NullableWorkspaceInput {
	return &NullableWorkspaceInput{value: val, isSet: true}
}

func (v NullableWorkspaceInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


