/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
)

// checks if the PaginationMetaMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginationMetaMeta{}

// PaginationMetaMeta struct for PaginationMetaMeta
type PaginationMetaMeta struct {
	CurrentPage *int32 `json:"current_page,omitempty"`
	From *int32 `json:"from,omitempty"`
	LastPage *int32 `json:"last_page,omitempty"`
	PerPage *int32 `json:"per_page,omitempty"`
	To *int32 `json:"to,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewPaginationMetaMeta instantiates a new PaginationMetaMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginationMetaMeta() *PaginationMetaMeta {
	this := PaginationMetaMeta{}
	return &this
}

// NewPaginationMetaMetaWithDefaults instantiates a new PaginationMetaMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginationMetaMetaWithDefaults() *PaginationMetaMeta {
	this := PaginationMetaMeta{}
	return &this
}

// GetCurrentPage returns the CurrentPage field value if set, zero value otherwise.
func (o *PaginationMetaMeta) GetCurrentPage() int32 {
	if o == nil || IsNil(o.CurrentPage) {
		var ret int32
		return ret
	}
	return *o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationMetaMeta) GetCurrentPageOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentPage) {
		return nil, false
	}
	return o.CurrentPage, true
}

// HasCurrentPage returns a boolean if a field has been set.
func (o *PaginationMetaMeta) HasCurrentPage() bool {
	if o != nil && !IsNil(o.CurrentPage) {
		return true
	}

	return false
}

// SetCurrentPage gets a reference to the given int32 and assigns it to the CurrentPage field.
func (o *PaginationMetaMeta) SetCurrentPage(v int32) {
	o.CurrentPage = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *PaginationMetaMeta) GetFrom() int32 {
	if o == nil || IsNil(o.From) {
		var ret int32
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationMetaMeta) GetFromOk() (*int32, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *PaginationMetaMeta) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given int32 and assigns it to the From field.
func (o *PaginationMetaMeta) SetFrom(v int32) {
	o.From = &v
}

// GetLastPage returns the LastPage field value if set, zero value otherwise.
func (o *PaginationMetaMeta) GetLastPage() int32 {
	if o == nil || IsNil(o.LastPage) {
		var ret int32
		return ret
	}
	return *o.LastPage
}

// GetLastPageOk returns a tuple with the LastPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationMetaMeta) GetLastPageOk() (*int32, bool) {
	if o == nil || IsNil(o.LastPage) {
		return nil, false
	}
	return o.LastPage, true
}

// HasLastPage returns a boolean if a field has been set.
func (o *PaginationMetaMeta) HasLastPage() bool {
	if o != nil && !IsNil(o.LastPage) {
		return true
	}

	return false
}

// SetLastPage gets a reference to the given int32 and assigns it to the LastPage field.
func (o *PaginationMetaMeta) SetLastPage(v int32) {
	o.LastPage = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *PaginationMetaMeta) GetPerPage() int32 {
	if o == nil || IsNil(o.PerPage) {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationMetaMeta) GetPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *PaginationMetaMeta) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *PaginationMetaMeta) SetPerPage(v int32) {
	o.PerPage = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *PaginationMetaMeta) GetTo() int32 {
	if o == nil || IsNil(o.To) {
		var ret int32
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationMetaMeta) GetToOk() (*int32, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *PaginationMetaMeta) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given int32 and assigns it to the To field.
func (o *PaginationMetaMeta) SetTo(v int32) {
	o.To = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *PaginationMetaMeta) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaginationMetaMeta) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *PaginationMetaMeta) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *PaginationMetaMeta) SetTotal(v int32) {
	o.Total = &v
}

func (o PaginationMetaMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginationMetaMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CurrentPage) {
		toSerialize["current_page"] = o.CurrentPage
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.LastPage) {
		toSerialize["last_page"] = o.LastPage
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullablePaginationMetaMeta struct {
	value *PaginationMetaMeta
	isSet bool
}

func (v NullablePaginationMetaMeta) Get() *PaginationMetaMeta {
	return v.value
}

func (v *NullablePaginationMetaMeta) Set(val *PaginationMetaMeta) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginationMetaMeta) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginationMetaMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginationMetaMeta(val *PaginationMetaMeta) *NullablePaginationMetaMeta {
	return &NullablePaginationMetaMeta{value: val, isSet: true}
}

func (v NullablePaginationMetaMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginationMetaMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


