/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
)

// checks if the UploadChunk200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadChunk200Response{}

// UploadChunk200Response struct for UploadChunk200Response
type UploadChunk200Response struct {
	// Number of chunks received so far.
	Received *int32 `json:"received,omitempty"`
}

// NewUploadChunk200Response instantiates a new UploadChunk200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadChunk200Response() *UploadChunk200Response {
	this := UploadChunk200Response{}
	return &this
}

// NewUploadChunk200ResponseWithDefaults instantiates a new UploadChunk200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadChunk200ResponseWithDefaults() *UploadChunk200Response {
	this := UploadChunk200Response{}
	return &this
}

// GetReceived returns the Received field value if set, zero value otherwise.
func (o *UploadChunk200Response) GetReceived() int32 {
	if o == nil || IsNil(o.Received) {
		var ret int32
		return ret
	}
	return *o.Received
}

// GetReceivedOk returns a tuple with the Received field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadChunk200Response) GetReceivedOk() (*int32, bool) {
	if o == nil || IsNil(o.Received) {
		return nil, false
	}
	return o.Received, true
}

// HasReceived returns a boolean if a field has been set.
func (o *UploadChunk200Response) HasReceived() bool {
	if o != nil && !IsNil(o.Received) {
		return true
	}

	return false
}

// SetReceived gets a reference to the given int32 and assigns it to the Received field.
func (o *UploadChunk200Response) SetReceived(v int32) {
	o.Received = &v
}

func (o UploadChunk200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadChunk200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Received) {
		toSerialize["received"] = o.Received
	}
	return toSerialize, nil
}

type NullableUploadChunk200Response struct {
	value *UploadChunk200Response
	isSet bool
}

func (v NullableUploadChunk200Response) Get() *UploadChunk200Response {
	return v.value
}

func (v *NullableUploadChunk200Response) Set(val *UploadChunk200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadChunk200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadChunk200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadChunk200Response(val *UploadChunk200Response) *NullableUploadChunk200Response {
	return &NullableUploadChunk200Response{value: val, isSet: true}
}

func (v NullableUploadChunk200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadChunk200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


