/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the SubscriptionInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionInput{}

// SubscriptionInput struct for SubscriptionInput
type SubscriptionInput struct {
	PlatformSubscriptionId string `json:"platform_subscription_id"`
	PlatformPlanId string `json:"platform_plan_id"`
	Status SubscriptionStatus `json:"status"`
	// Required when status is `trialing`.
	TrialEndsAt *time.Time `json:"trial_ends_at,omitempty"`
}

type _SubscriptionInput SubscriptionInput

// NewSubscriptionInput instantiates a new SubscriptionInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionInput(platformSubscriptionId string, platformPlanId string, status SubscriptionStatus) *SubscriptionInput {
	this := SubscriptionInput{}
	this.PlatformSubscriptionId = platformSubscriptionId
	this.PlatformPlanId = platformPlanId
	this.Status = status
	return &this
}

// NewSubscriptionInputWithDefaults instantiates a new SubscriptionInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionInputWithDefaults() *SubscriptionInput {
	this := SubscriptionInput{}
	return &this
}

// GetPlatformSubscriptionId returns the PlatformSubscriptionId field value
func (o *SubscriptionInput) GetPlatformSubscriptionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlatformSubscriptionId
}

// GetPlatformSubscriptionIdOk returns a tuple with the PlatformSubscriptionId field value
// and a boolean to check if the value has been set.
func (o *SubscriptionInput) GetPlatformSubscriptionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlatformSubscriptionId, true
}

// SetPlatformSubscriptionId sets field value
func (o *SubscriptionInput) SetPlatformSubscriptionId(v string) {
	o.PlatformSubscriptionId = v
}

// GetPlatformPlanId returns the PlatformPlanId field value
func (o *SubscriptionInput) GetPlatformPlanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlatformPlanId
}

// GetPlatformPlanIdOk returns a tuple with the PlatformPlanId field value
// and a boolean to check if the value has been set.
func (o *SubscriptionInput) GetPlatformPlanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlatformPlanId, true
}

// SetPlatformPlanId sets field value
func (o *SubscriptionInput) SetPlatformPlanId(v string) {
	o.PlatformPlanId = v
}

// GetStatus returns the Status field value
func (o *SubscriptionInput) GetStatus() SubscriptionStatus {
	if o == nil {
		var ret SubscriptionStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SubscriptionInput) GetStatusOk() (*SubscriptionStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SubscriptionInput) SetStatus(v SubscriptionStatus) {
	o.Status = v
}

// GetTrialEndsAt returns the TrialEndsAt field value if set, zero value otherwise.
func (o *SubscriptionInput) GetTrialEndsAt() time.Time {
	if o == nil || IsNil(o.TrialEndsAt) {
		var ret time.Time
		return ret
	}
	return *o.TrialEndsAt
}

// GetTrialEndsAtOk returns a tuple with the TrialEndsAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionInput) GetTrialEndsAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TrialEndsAt) {
		return nil, false
	}
	return o.TrialEndsAt, true
}

// HasTrialEndsAt returns a boolean if a field has been set.
func (o *SubscriptionInput) HasTrialEndsAt() bool {
	if o != nil && !IsNil(o.TrialEndsAt) {
		return true
	}

	return false
}

// SetTrialEndsAt gets a reference to the given time.Time and assigns it to the TrialEndsAt field.
func (o *SubscriptionInput) SetTrialEndsAt(v time.Time) {
	o.TrialEndsAt = &v
}

func (o SubscriptionInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["platform_subscription_id"] = o.PlatformSubscriptionId
	toSerialize["platform_plan_id"] = o.PlatformPlanId
	toSerialize["status"] = o.Status
	if !IsNil(o.TrialEndsAt) {
		toSerialize["trial_ends_at"] = o.TrialEndsAt
	}
	return toSerialize, nil
}

func (o *SubscriptionInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"platform_subscription_id",
		"platform_plan_id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubscriptionInput := _SubscriptionInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubscriptionInput)

	if err != nil {
		return err
	}

	*o = SubscriptionInput(varSubscriptionInput)

	return err
}

type NullableSubscriptionInput struct {
	value *SubscriptionInput
	isSet bool
}

func (v NullableSubscriptionInput) Get() *SubscriptionInput {
	return v.value
}

func (v *NullableSubscriptionInput) Set(val *SubscriptionInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionInput(val *SubscriptionInput) *NullableSubscriptionInput {
	return &NullableSubscriptionInput{value: val, isSet: true}
}

func (v NullableSubscriptionInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


