/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ImageGenerate200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageGenerate200Response{}

// ImageGenerate200Response struct for ImageGenerate200Response
type ImageGenerate200Response struct {
	Data ImageGenerationResponse `json:"data"`
}

type _ImageGenerate200Response ImageGenerate200Response

// NewImageGenerate200Response instantiates a new ImageGenerate200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageGenerate200Response(data ImageGenerationResponse) *ImageGenerate200Response {
	this := ImageGenerate200Response{}
	this.Data = data
	return &this
}

// NewImageGenerate200ResponseWithDefaults instantiates a new ImageGenerate200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageGenerate200ResponseWithDefaults() *ImageGenerate200Response {
	this := ImageGenerate200Response{}
	return &this
}

// GetData returns the Data field value
func (o *ImageGenerate200Response) GetData() ImageGenerationResponse {
	if o == nil {
		var ret ImageGenerationResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ImageGenerate200Response) GetDataOk() (*ImageGenerationResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ImageGenerate200Response) SetData(v ImageGenerationResponse) {
	o.Data = v
}

func (o ImageGenerate200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageGenerate200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ImageGenerate200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImageGenerate200Response := _ImageGenerate200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImageGenerate200Response)

	if err != nil {
		return err
	}

	*o = ImageGenerate200Response(varImageGenerate200Response)

	return err
}

type NullableImageGenerate200Response struct {
	value *ImageGenerate200Response
	isSet bool
}

func (v NullableImageGenerate200Response) Get() *ImageGenerate200Response {
	return v.value
}

func (v *NullableImageGenerate200Response) Set(val *ImageGenerate200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableImageGenerate200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableImageGenerate200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageGenerate200Response(val *ImageGenerate200Response) *NullableImageGenerate200Response {
	return &NullableImageGenerate200Response{value: val, isSet: true}
}

func (v NullableImageGenerate200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageGenerate200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


