/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
)

// checks if the DeletePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeletePostRequest{}

// DeletePostRequest struct for DeletePostRequest
type DeletePostRequest struct {
	Trash *bool `json:"trash,omitempty"`
	DeleteMode *DeleteMode `json:"delete_mode,omitempty"`
}

// NewDeletePostRequest instantiates a new DeletePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletePostRequest() *DeletePostRequest {
	this := DeletePostRequest{}
	var trash bool = false
	this.Trash = &trash
	var deleteMode DeleteMode = APP_ONLY
	this.DeleteMode = &deleteMode
	return &this
}

// NewDeletePostRequestWithDefaults instantiates a new DeletePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletePostRequestWithDefaults() *DeletePostRequest {
	this := DeletePostRequest{}
	var trash bool = false
	this.Trash = &trash
	var deleteMode DeleteMode = APP_ONLY
	this.DeleteMode = &deleteMode
	return &this
}

// GetTrash returns the Trash field value if set, zero value otherwise.
func (o *DeletePostRequest) GetTrash() bool {
	if o == nil || IsNil(o.Trash) {
		var ret bool
		return ret
	}
	return *o.Trash
}

// GetTrashOk returns a tuple with the Trash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletePostRequest) GetTrashOk() (*bool, bool) {
	if o == nil || IsNil(o.Trash) {
		return nil, false
	}
	return o.Trash, true
}

// HasTrash returns a boolean if a field has been set.
func (o *DeletePostRequest) HasTrash() bool {
	if o != nil && !IsNil(o.Trash) {
		return true
	}

	return false
}

// SetTrash gets a reference to the given bool and assigns it to the Trash field.
func (o *DeletePostRequest) SetTrash(v bool) {
	o.Trash = &v
}

// GetDeleteMode returns the DeleteMode field value if set, zero value otherwise.
func (o *DeletePostRequest) GetDeleteMode() DeleteMode {
	if o == nil || IsNil(o.DeleteMode) {
		var ret DeleteMode
		return ret
	}
	return *o.DeleteMode
}

// GetDeleteModeOk returns a tuple with the DeleteMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeletePostRequest) GetDeleteModeOk() (*DeleteMode, bool) {
	if o == nil || IsNil(o.DeleteMode) {
		return nil, false
	}
	return o.DeleteMode, true
}

// HasDeleteMode returns a boolean if a field has been set.
func (o *DeletePostRequest) HasDeleteMode() bool {
	if o != nil && !IsNil(o.DeleteMode) {
		return true
	}

	return false
}

// SetDeleteMode gets a reference to the given DeleteMode and assigns it to the DeleteMode field.
func (o *DeletePostRequest) SetDeleteMode(v DeleteMode) {
	o.DeleteMode = &v
}

func (o DeletePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Trash) {
		toSerialize["trash"] = o.Trash
	}
	if !IsNil(o.DeleteMode) {
		toSerialize["delete_mode"] = o.DeleteMode
	}
	return toSerialize, nil
}

type NullableDeletePostRequest struct {
	value *DeletePostRequest
	isSet bool
}

func (v NullableDeletePostRequest) Get() *DeletePostRequest {
	return v.value
}

func (v *NullableDeletePostRequest) Set(val *DeletePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletePostRequest(val *DeletePostRequest) *NullableDeletePostRequest {
	return &NullableDeletePostRequest{value: val, isSet: true}
}

func (v NullableDeletePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


