/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
)

// checks if the BlogToSocialCaption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlogToSocialCaption{}

// BlogToSocialCaption struct for BlogToSocialCaption
type BlogToSocialCaption struct {
	// ID of the social account this caption was generated for.
	AccountId *int32 `json:"account_id,omitempty"`
	// Social media platform identifier.
	Provider *string `json:"provider,omitempty"`
	// The generated caption text. `null` if generation failed for this account.
	Content *string `json:"content,omitempty"`
	// Character count of the generated content. `null` if generation failed.
	CharacterCount *int32 `json:"character_count,omitempty"`
	// Maximum allowed character count for this platform.
	CharacterLimit *int32 `json:"character_limit,omitempty"`
	// Error message if caption generation failed for this account. `null` on success.
	Error *string `json:"error,omitempty"`
}

// NewBlogToSocialCaption instantiates a new BlogToSocialCaption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlogToSocialCaption() *BlogToSocialCaption {
	this := BlogToSocialCaption{}
	return &this
}

// NewBlogToSocialCaptionWithDefaults instantiates a new BlogToSocialCaption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlogToSocialCaptionWithDefaults() *BlogToSocialCaption {
	this := BlogToSocialCaption{}
	return &this
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *BlogToSocialCaption) GetAccountId() int32 {
	if o == nil || IsNil(o.AccountId) {
		var ret int32
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlogToSocialCaption) GetAccountIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *BlogToSocialCaption) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given int32 and assigns it to the AccountId field.
func (o *BlogToSocialCaption) SetAccountId(v int32) {
	o.AccountId = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *BlogToSocialCaption) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlogToSocialCaption) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *BlogToSocialCaption) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *BlogToSocialCaption) SetProvider(v string) {
	o.Provider = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *BlogToSocialCaption) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlogToSocialCaption) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *BlogToSocialCaption) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *BlogToSocialCaption) SetContent(v string) {
	o.Content = &v
}

// GetCharacterCount returns the CharacterCount field value if set, zero value otherwise.
func (o *BlogToSocialCaption) GetCharacterCount() int32 {
	if o == nil || IsNil(o.CharacterCount) {
		var ret int32
		return ret
	}
	return *o.CharacterCount
}

// GetCharacterCountOk returns a tuple with the CharacterCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlogToSocialCaption) GetCharacterCountOk() (*int32, bool) {
	if o == nil || IsNil(o.CharacterCount) {
		return nil, false
	}
	return o.CharacterCount, true
}

// HasCharacterCount returns a boolean if a field has been set.
func (o *BlogToSocialCaption) HasCharacterCount() bool {
	if o != nil && !IsNil(o.CharacterCount) {
		return true
	}

	return false
}

// SetCharacterCount gets a reference to the given int32 and assigns it to the CharacterCount field.
func (o *BlogToSocialCaption) SetCharacterCount(v int32) {
	o.CharacterCount = &v
}

// GetCharacterLimit returns the CharacterLimit field value if set, zero value otherwise.
func (o *BlogToSocialCaption) GetCharacterLimit() int32 {
	if o == nil || IsNil(o.CharacterLimit) {
		var ret int32
		return ret
	}
	return *o.CharacterLimit
}

// GetCharacterLimitOk returns a tuple with the CharacterLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlogToSocialCaption) GetCharacterLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.CharacterLimit) {
		return nil, false
	}
	return o.CharacterLimit, true
}

// HasCharacterLimit returns a boolean if a field has been set.
func (o *BlogToSocialCaption) HasCharacterLimit() bool {
	if o != nil && !IsNil(o.CharacterLimit) {
		return true
	}

	return false
}

// SetCharacterLimit gets a reference to the given int32 and assigns it to the CharacterLimit field.
func (o *BlogToSocialCaption) SetCharacterLimit(v int32) {
	o.CharacterLimit = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *BlogToSocialCaption) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlogToSocialCaption) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *BlogToSocialCaption) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *BlogToSocialCaption) SetError(v string) {
	o.Error = &v
}

func (o BlogToSocialCaption) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlogToSocialCaption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.CharacterCount) {
		toSerialize["character_count"] = o.CharacterCount
	}
	if !IsNil(o.CharacterLimit) {
		toSerialize["character_limit"] = o.CharacterLimit
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableBlogToSocialCaption struct {
	value *BlogToSocialCaption
	isSet bool
}

func (v NullableBlogToSocialCaption) Get() *BlogToSocialCaption {
	return v.value
}

func (v *NullableBlogToSocialCaption) Set(val *BlogToSocialCaption) {
	v.value = val
	v.isSet = true
}

func (v NullableBlogToSocialCaption) IsSet() bool {
	return v.isSet
}

func (v *NullableBlogToSocialCaption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlogToSocialCaption(val *BlogToSocialCaption) *NullableBlogToSocialCaption {
	return &NullableBlogToSocialCaption{value: val, isSet: true}
}

func (v NullableBlogToSocialCaption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlogToSocialCaption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


