/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Receipt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Receipt{}

// Receipt struct for Receipt
type Receipt struct {
	Uuid string `json:"uuid"`
	TransactionId string `json:"transaction_id"`
	InvoiceNumber string `json:"invoice_number"`
	Amount float32 `json:"amount"`
	Tax float32 `json:"tax"`
	Currency string `json:"currency"`
	ReceiptUrl *string `json:"receipt_url,omitempty"`
	Description *string `json:"description,omitempty"`
	PaidAt time.Time `json:"paid_at"`
	CreatedAt time.Time `json:"created_at"`
}

type _Receipt Receipt

// NewReceipt instantiates a new Receipt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReceipt(uuid string, transactionId string, invoiceNumber string, amount float32, tax float32, currency string, paidAt time.Time, createdAt time.Time) *Receipt {
	this := Receipt{}
	this.Uuid = uuid
	this.TransactionId = transactionId
	this.InvoiceNumber = invoiceNumber
	this.Amount = amount
	this.Tax = tax
	this.Currency = currency
	this.PaidAt = paidAt
	this.CreatedAt = createdAt
	return &this
}

// NewReceiptWithDefaults instantiates a new Receipt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReceiptWithDefaults() *Receipt {
	this := Receipt{}
	return &this
}

// GetUuid returns the Uuid field value
func (o *Receipt) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *Receipt) SetUuid(v string) {
	o.Uuid = v
}

// GetTransactionId returns the TransactionId field value
func (o *Receipt) GetTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionId, true
}

// SetTransactionId sets field value
func (o *Receipt) SetTransactionId(v string) {
	o.TransactionId = v
}

// GetInvoiceNumber returns the InvoiceNumber field value
func (o *Receipt) GetInvoiceNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InvoiceNumber
}

// GetInvoiceNumberOk returns a tuple with the InvoiceNumber field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetInvoiceNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvoiceNumber, true
}

// SetInvoiceNumber sets field value
func (o *Receipt) SetInvoiceNumber(v string) {
	o.InvoiceNumber = v
}

// GetAmount returns the Amount field value
func (o *Receipt) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *Receipt) SetAmount(v float32) {
	o.Amount = v
}

// GetTax returns the Tax field value
func (o *Receipt) GetTax() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Tax
}

// GetTaxOk returns a tuple with the Tax field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetTaxOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tax, true
}

// SetTax sets field value
func (o *Receipt) SetTax(v float32) {
	o.Tax = v
}

// GetCurrency returns the Currency field value
func (o *Receipt) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *Receipt) SetCurrency(v string) {
	o.Currency = v
}

// GetReceiptUrl returns the ReceiptUrl field value if set, zero value otherwise.
func (o *Receipt) GetReceiptUrl() string {
	if o == nil || IsNil(o.ReceiptUrl) {
		var ret string
		return ret
	}
	return *o.ReceiptUrl
}

// GetReceiptUrlOk returns a tuple with the ReceiptUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetReceiptUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ReceiptUrl) {
		return nil, false
	}
	return o.ReceiptUrl, true
}

// HasReceiptUrl returns a boolean if a field has been set.
func (o *Receipt) HasReceiptUrl() bool {
	if o != nil && !IsNil(o.ReceiptUrl) {
		return true
	}

	return false
}

// SetReceiptUrl gets a reference to the given string and assigns it to the ReceiptUrl field.
func (o *Receipt) SetReceiptUrl(v string) {
	o.ReceiptUrl = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Receipt) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Receipt) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Receipt) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Receipt) SetDescription(v string) {
	o.Description = &v
}

// GetPaidAt returns the PaidAt field value
func (o *Receipt) GetPaidAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.PaidAt
}

// GetPaidAtOk returns a tuple with the PaidAt field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetPaidAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaidAt, true
}

// SetPaidAt sets field value
func (o *Receipt) SetPaidAt(v time.Time) {
	o.PaidAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Receipt) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Receipt) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Receipt) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o Receipt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Receipt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["transaction_id"] = o.TransactionId
	toSerialize["invoice_number"] = o.InvoiceNumber
	toSerialize["amount"] = o.Amount
	toSerialize["tax"] = o.Tax
	toSerialize["currency"] = o.Currency
	if !IsNil(o.ReceiptUrl) {
		toSerialize["receipt_url"] = o.ReceiptUrl
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["paid_at"] = o.PaidAt
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *Receipt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"transaction_id",
		"invoice_number",
		"amount",
		"tax",
		"currency",
		"paid_at",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReceipt := _Receipt{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReceipt)

	if err != nil {
		return err
	}

	*o = Receipt(varReceipt)

	return err
}

type NullableReceipt struct {
	value *Receipt
	isSet bool
}

func (v NullableReceipt) Get() *Receipt {
	return v.value
}

func (v *NullableReceipt) Set(val *Receipt) {
	v.value = val
	v.isSet = true
}

func (v NullableReceipt) IsSet() bool {
	return v.isSet
}

func (v *NullableReceipt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReceipt(val *Receipt) *NullableReceipt {
	return &NullableReceipt{value: val, isSet: true}
}

func (v NullableReceipt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReceipt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


