/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// InitiateRemoteUpload200Response - struct for InitiateRemoteUpload200Response
type InitiateRemoteUpload200Response struct {
	InitiateRemoteUpload200ResponseOneOf *InitiateRemoteUpload200ResponseOneOf
	Media *Media
}

// InitiateRemoteUpload200ResponseOneOfAsInitiateRemoteUpload200Response is a convenience function that returns InitiateRemoteUpload200ResponseOneOf wrapped in InitiateRemoteUpload200Response
func InitiateRemoteUpload200ResponseOneOfAsInitiateRemoteUpload200Response(v *InitiateRemoteUpload200ResponseOneOf) InitiateRemoteUpload200Response {
	return InitiateRemoteUpload200Response{
		InitiateRemoteUpload200ResponseOneOf: v,
	}
}

// MediaAsInitiateRemoteUpload200Response is a convenience function that returns Media wrapped in InitiateRemoteUpload200Response
func MediaAsInitiateRemoteUpload200Response(v *Media) InitiateRemoteUpload200Response {
	return InitiateRemoteUpload200Response{
		Media: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *InitiateRemoteUpload200Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into InitiateRemoteUpload200ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.InitiateRemoteUpload200ResponseOneOf)
	if err == nil {
		jsonInitiateRemoteUpload200ResponseOneOf, _ := json.Marshal(dst.InitiateRemoteUpload200ResponseOneOf)
		if string(jsonInitiateRemoteUpload200ResponseOneOf) == "{}" { // empty struct
			dst.InitiateRemoteUpload200ResponseOneOf = nil
		} else {
			if err = validator.Validate(dst.InitiateRemoteUpload200ResponseOneOf); err != nil {
				dst.InitiateRemoteUpload200ResponseOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.InitiateRemoteUpload200ResponseOneOf = nil
	}

	// try to unmarshal data into Media
	err = newStrictDecoder(data).Decode(&dst.Media)
	if err == nil {
		jsonMedia, _ := json.Marshal(dst.Media)
		if string(jsonMedia) == "{}" { // empty struct
			dst.Media = nil
		} else {
			if err = validator.Validate(dst.Media); err != nil {
				dst.Media = nil
			} else {
				match++
			}
		}
	} else {
		dst.Media = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.InitiateRemoteUpload200ResponseOneOf = nil
		dst.Media = nil

		return fmt.Errorf("data matches more than one schema in oneOf(InitiateRemoteUpload200Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(InitiateRemoteUpload200Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src InitiateRemoteUpload200Response) MarshalJSON() ([]byte, error) {
	if src.InitiateRemoteUpload200ResponseOneOf != nil {
		return json.Marshal(&src.InitiateRemoteUpload200ResponseOneOf)
	}

	if src.Media != nil {
		return json.Marshal(&src.Media)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *InitiateRemoteUpload200Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.InitiateRemoteUpload200ResponseOneOf != nil {
		return obj.InitiateRemoteUpload200ResponseOneOf
	}

	if obj.Media != nil {
		return obj.Media
	}

	// all schemas are nil
	return nil
}

type NullableInitiateRemoteUpload200Response struct {
	value *InitiateRemoteUpload200Response
	isSet bool
}

func (v NullableInitiateRemoteUpload200Response) Get() *InitiateRemoteUpload200Response {
	return v.value
}

func (v *NullableInitiateRemoteUpload200Response) Set(val *InitiateRemoteUpload200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiateRemoteUpload200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiateRemoteUpload200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiateRemoteUpload200Response(val *InitiateRemoteUpload200Response) *NullableInitiateRemoteUpload200Response {
	return &NullableInitiateRemoteUpload200Response{value: val, isSet: true}
}

func (v NullableInitiateRemoteUpload200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiateRemoteUpload200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


