/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddGenericSubscriptionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddGenericSubscriptionRequest{}

// AddGenericSubscriptionRequest struct for AddGenericSubscriptionRequest
type AddGenericSubscriptionRequest struct {
	PlanId int32 `json:"plan_id"`
	TrialDays *int32 `json:"trial_days,omitempty"`
	KeepPrevTrialEndsAt bool `json:"keep_prev_trial_ends_at"`
}

type _AddGenericSubscriptionRequest AddGenericSubscriptionRequest

// NewAddGenericSubscriptionRequest instantiates a new AddGenericSubscriptionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddGenericSubscriptionRequest(planId int32, keepPrevTrialEndsAt bool) *AddGenericSubscriptionRequest {
	this := AddGenericSubscriptionRequest{}
	this.PlanId = planId
	this.KeepPrevTrialEndsAt = keepPrevTrialEndsAt
	return &this
}

// NewAddGenericSubscriptionRequestWithDefaults instantiates a new AddGenericSubscriptionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddGenericSubscriptionRequestWithDefaults() *AddGenericSubscriptionRequest {
	this := AddGenericSubscriptionRequest{}
	return &this
}

// GetPlanId returns the PlanId field value
func (o *AddGenericSubscriptionRequest) GetPlanId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PlanId
}

// GetPlanIdOk returns a tuple with the PlanId field value
// and a boolean to check if the value has been set.
func (o *AddGenericSubscriptionRequest) GetPlanIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlanId, true
}

// SetPlanId sets field value
func (o *AddGenericSubscriptionRequest) SetPlanId(v int32) {
	o.PlanId = v
}

// GetTrialDays returns the TrialDays field value if set, zero value otherwise.
func (o *AddGenericSubscriptionRequest) GetTrialDays() int32 {
	if o == nil || IsNil(o.TrialDays) {
		var ret int32
		return ret
	}
	return *o.TrialDays
}

// GetTrialDaysOk returns a tuple with the TrialDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddGenericSubscriptionRequest) GetTrialDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.TrialDays) {
		return nil, false
	}
	return o.TrialDays, true
}

// HasTrialDays returns a boolean if a field has been set.
func (o *AddGenericSubscriptionRequest) HasTrialDays() bool {
	if o != nil && !IsNil(o.TrialDays) {
		return true
	}

	return false
}

// SetTrialDays gets a reference to the given int32 and assigns it to the TrialDays field.
func (o *AddGenericSubscriptionRequest) SetTrialDays(v int32) {
	o.TrialDays = &v
}

// GetKeepPrevTrialEndsAt returns the KeepPrevTrialEndsAt field value
func (o *AddGenericSubscriptionRequest) GetKeepPrevTrialEndsAt() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.KeepPrevTrialEndsAt
}

// GetKeepPrevTrialEndsAtOk returns a tuple with the KeepPrevTrialEndsAt field value
// and a boolean to check if the value has been set.
func (o *AddGenericSubscriptionRequest) GetKeepPrevTrialEndsAtOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.KeepPrevTrialEndsAt, true
}

// SetKeepPrevTrialEndsAt sets field value
func (o *AddGenericSubscriptionRequest) SetKeepPrevTrialEndsAt(v bool) {
	o.KeepPrevTrialEndsAt = v
}

func (o AddGenericSubscriptionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddGenericSubscriptionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plan_id"] = o.PlanId
	if !IsNil(o.TrialDays) {
		toSerialize["trial_days"] = o.TrialDays
	}
	toSerialize["keep_prev_trial_ends_at"] = o.KeepPrevTrialEndsAt
	return toSerialize, nil
}

func (o *AddGenericSubscriptionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plan_id",
		"keep_prev_trial_ends_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddGenericSubscriptionRequest := _AddGenericSubscriptionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddGenericSubscriptionRequest)

	if err != nil {
		return err
	}

	*o = AddGenericSubscriptionRequest(varAddGenericSubscriptionRequest)

	return err
}

type NullableAddGenericSubscriptionRequest struct {
	value *AddGenericSubscriptionRequest
	isSet bool
}

func (v NullableAddGenericSubscriptionRequest) Get() *AddGenericSubscriptionRequest {
	return v.value
}

func (v *NullableAddGenericSubscriptionRequest) Set(val *AddGenericSubscriptionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddGenericSubscriptionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddGenericSubscriptionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddGenericSubscriptionRequest(val *AddGenericSubscriptionRequest) *NullableAddGenericSubscriptionRequest {
	return &NullableAddGenericSubscriptionRequest{value: val, isSet: true}
}

func (v NullableAddGenericSubscriptionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddGenericSubscriptionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


