/*
PostBoost API

The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 

API version: 1.0.0
Contact: hi@postboost.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package postboost

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GeneratedImageItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeneratedImageItem{}

// GeneratedImageItem struct for GeneratedImageItem
type GeneratedImageItem struct {
	MediaId int32 `json:"media_id"`
	Url string `json:"url"`
	ThumbUrl string `json:"thumb_url"`
}

type _GeneratedImageItem GeneratedImageItem

// NewGeneratedImageItem instantiates a new GeneratedImageItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeneratedImageItem(mediaId int32, url string, thumbUrl string) *GeneratedImageItem {
	this := GeneratedImageItem{}
	this.MediaId = mediaId
	this.Url = url
	this.ThumbUrl = thumbUrl
	return &this
}

// NewGeneratedImageItemWithDefaults instantiates a new GeneratedImageItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeneratedImageItemWithDefaults() *GeneratedImageItem {
	this := GeneratedImageItem{}
	return &this
}

// GetMediaId returns the MediaId field value
func (o *GeneratedImageItem) GetMediaId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MediaId
}

// GetMediaIdOk returns a tuple with the MediaId field value
// and a boolean to check if the value has been set.
func (o *GeneratedImageItem) GetMediaIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MediaId, true
}

// SetMediaId sets field value
func (o *GeneratedImageItem) SetMediaId(v int32) {
	o.MediaId = v
}

// GetUrl returns the Url field value
func (o *GeneratedImageItem) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *GeneratedImageItem) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *GeneratedImageItem) SetUrl(v string) {
	o.Url = v
}

// GetThumbUrl returns the ThumbUrl field value
func (o *GeneratedImageItem) GetThumbUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ThumbUrl
}

// GetThumbUrlOk returns a tuple with the ThumbUrl field value
// and a boolean to check if the value has been set.
func (o *GeneratedImageItem) GetThumbUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThumbUrl, true
}

// SetThumbUrl sets field value
func (o *GeneratedImageItem) SetThumbUrl(v string) {
	o.ThumbUrl = v
}

func (o GeneratedImageItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeneratedImageItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["media_id"] = o.MediaId
	toSerialize["url"] = o.Url
	toSerialize["thumb_url"] = o.ThumbUrl
	return toSerialize, nil
}

func (o *GeneratedImageItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"media_id",
		"url",
		"thumb_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGeneratedImageItem := _GeneratedImageItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGeneratedImageItem)

	if err != nil {
		return err
	}

	*o = GeneratedImageItem(varGeneratedImageItem)

	return err
}

type NullableGeneratedImageItem struct {
	value *GeneratedImageItem
	isSet bool
}

func (v NullableGeneratedImageItem) Get() *GeneratedImageItem {
	return v.value
}

func (v *NullableGeneratedImageItem) Set(val *GeneratedImageItem) {
	v.value = val
	v.isSet = true
}

func (v NullableGeneratedImageItem) IsSet() bool {
	return v.isSet
}

func (v *NullableGeneratedImageItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeneratedImageItem(val *GeneratedImageItem) *NullableGeneratedImageItem {
	return &NullableGeneratedImageItem{value: val, isSet: true}
}

func (v NullableGeneratedImageItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeneratedImageItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


